version: '3.7'
services:
  traefik:
    container_name: proxy
    image: traefik:1.7.2-alpine
    command: --web --docker
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/traefik.toml
    networks:
      - frontends
      - backends
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - './mongoDB/:/data/db'
    expose:
      - '27017'
    ports:
      - '27017:27017'
    labels:
      - 'traefik.enable=false'
    networks:
      - frontends
      - backends
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-alpine
    expose:
      - '5672'
    ports:
      - '8081:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: development
      RABBITMQ_DEFAULT_PASS: development
    labels:
      - 'traefik.enable=false'
    networks:
      - frontends
      - backends
networks:
  frontends:
    name: custom_frontend_networks
  backends:
    name: custom_backend_networks
