version: '3.5'
services:
  traefik:
    container_name: proxy
    image: traefik:1.7.2-alpine
    command: --web --docker
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.toml:/traefik.toml
  angular:
    image: nginx:1.17-alpine
    ports:
      - '81:81'
    environment:
      - NGINX_HOST=www.localhost
      - NGINX_PORT=81
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:www.localhost'
  web2:
    image: nginx:1.17-alpine
    ports:
      - '82:82'
    environment:
      - NGINX_HOST=web2.localhost
      - NGINX_PORT=82
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:web2.localhost'
