debug = true
logLevel = "DEBUG"

defaultEntryPoints = ["https", "http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]


[frontends]
    [frontends.polsec_ai_front]
    backend = "storage_api"
        [frontends.polsec_ai_front.routes.rota_1]
        rule = "Host:dev-polsecai.polsecled.com"
        port = 81

[backends]
    [backends.storage_api]
        [backends.storage_api.servers.storage_api]
        rule = "Host:dev-storage.polsecled.com"
        url = "http://storage:3000"
        weigth = 1

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "polsecled.com"
watch = true
exposedByDefault = false

[acme]
email = "devops@polsec.ai"
storage = "acme.json"
onDemand = true
onHostRule = true
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"