debug = true
logLevel = "DEBUG"

defaultEntryPoint = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoint.https.tls]

[frontends]
    [frontends.angular]
    backend = "storage_api"
        [frontends.angular.routes.rota_1]
        rule = "Host:dev-polsecai.polsecled.com"
        port = 81


[backends]
    [backends.mongo]
        [backends.mongo.servers.mongo]
        rule = "Host:mongo.localhost"
        url = "http://mongo:27017"
        weigth = 0
    [backends.rabbitmq]
        [backends.rabbitmq.servers.rabbitmq]
        rule = "Host:rabbitmq.localhost"
        url = "http://rabbitmq:5672"
        weigth = 0
    [backends.storage_api]
        [backends.storage_api.servers.storage_api]
        rule = "Host:dev-storage.polsecled.com"
        url = "http://storage:3000"
        weigth = 1

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedByDefault = false

# [acme]
# email = "eluizbr@gmail.com"
# storage = "acme.json"
# onDemand = true
# entryPoint = "https"
# onHostRule = true
#   [acme.httpChallenge]
#   entryPoint = "http"